Task 6
Poddyman0/fe-nc-news pull request #1
Opened 2023-09-06 14:22 UTC by Poddyman0

2023-09-06 14:58 UTC, Hard-Luck requested changes
Lots of console.logs need removing too

2023-09-06 14:58 UTC, Hard-Luck commented on src/components/ChangeVotes.jsx
> +    setAlterVotes(data.article, { inc_votes : vote})
You would want to change the votes first for optimistic rendering and revert it in the case of an error

2023-09-06 14:58 UTC, Hard-Luck commented on src/components/ChangeVotes.jsx
> +    .then({data})
This should be an arrow function wrapping the rest of the content

2023-09-06 14:58 UTC, Hard-Luck commented on src/components/ChangeVotes.jsx
> +    <button onClick={increaseVotes(+1)}>Add vote</button>
here the increaseVotes function is being invoked immedaitely, I think you want to to be invoked when cliicked so look at wrapping it in a function ()=> increaseVotes(1)

2023-09-06 14:58 UTC, Hard-Luck commented on src/components/ChangeVotes.jsx
> +    .patch(`https://be-nc-news-tnfa.onrender.com/api/articles/${article_id}`)
This is giving an article_id does not exist, it might be worth looking at your back end

2023-09-07 10:26 UTC, merged

2023-09-07 10:49 UTC, Pipe-Smoking-Rabbit reviewed
Nice work on these tickets, here is some feedback from a user perspective:
- The landing / home page doesn't load any content, does there need to be a home page and an _All Articles_ page separately ? ( You might have future plans for the home page which is fine too )
- The Article List shows me the article ID for each one, as a user do I need to see that information ?
- The single article page doesn't show me the article body so as a user I can't read the article 
- The single article page has a label for _"Comment Count:"_ but it isn't currently showing the number
- The comments list renders nicely underneath the article page which feels like a good place for it to be 👍 
- As a user do I need to see the comment ID for each comment ?